# Generated by Django 3.0.8 on 2020-10-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
